### ISSUE TITLE
FasterMoE paper on PPoPP'22

### ISSUE THREAD

**Issue by laekov** [XueFuzhao/awesome-mixture-of-experts#1]
There is a new distributed system *FasterMoE: modeling and optimizing training of large-scale dynamic pre-trained models* published on [PPoPP'22](https://dl.acm.org/doi/abs/10.1145/3503221.3508418). As long as you have already put BaGuaLu in your list, please also kindly consider including this paper.

FYI, we have also indicated this paper collections at [FastMoE's homepage](https://fastmoe.ai/documentation/related-works.html#moe-paper-collections)

**Comment by XueFuzhao** [comment]
Cool! Thank you for your comments. Cong to your FasterMoE. Great work! Updated.
