### ISSUE TITLE
Dynamic Mixture of Experts

### ISSUE THREAD

**Issue by QAQdev** [XueFuzhao/awesome-mixture-of-experts#9]
We propose [_Dynamic Mixture of Experts: An Auto-Tuning Approach for Efficient Transformer Models_](https://arxiv.org/abs/2405.14297), a routing mechanism which allows for a variable number of experts per token as well as a procedure for dynamically changing the number of experts during training.

I think this may match your interest on adaptive computation! Please kindly consider including this paper.

We also provide our implementation at [LINs-lab/DynMoE](https://github.com/LINs-lab/DynMoE).

**Comment by XueFuzhao** [comment]
Hi,

Sounds cool!
Could you please submit a PR to add your paper?

Best,
Fuzhao

Zhenglin Cheng ***@***.***>于2024年6月25日 周二22:33写道：

**Comment by QAQdev** [comment]
Sure! Submitted a PR.
